### PR TITLE
Fixed repo name in snapshot flyout; Use schedule from policy during edit

### LINKED ISSUE #823: [BUG] UI issues in the Edit Snapshot Policy Page
**What is the bug?**
Once we create the Snapshot Management policy from the API/UI the following Options are reset to pre-set values during edit -

Start time in Snapshot Schedule. [20:00] [This Options is visible for any other snapshot frequency other than hourly]
Maximum age of snapshots retained in Specify Retention Conditions under Retention period. [1 days]

**How can one reproduce the bug?**
1. Create a Following Daily Snapshot Policy -

```
POST _plugins/_sm/policies/test-daily-snapshot
{
    "description": "Policy for Daily Snapshot",
    "creation": {
      "schedule": {
        "cron": {
          "expression": "0 0 * * *",
          "timezone": "UTC"
        }
      }
    },
    "deletion": {
      "schedule": {
        "cron": {
          "expression": "0 0 * * *",
          "timezone": "UTC"
        }
      },
      "condition": {
        "min_count": 1,
        "max_count": 100
      }
    },
    "snapshot_config": {
      "indices": "hot*,warm*",
      "repository": "test23"
    }
}
```
2. Navigate to the Snapshot Policy Page and select the policy following details would be visible, which are correct and expected -
image

3. But Now If we Click on Edit Button, following could be observed once the page completely loads -
image

**What is the expected behavior?**
1. The Start time field should use the value from the policy being edited.

**What is your host/environment?**
 - OS: 2.7 or less
 - Plugins: Index-management-dashboards plugin

**Do you have any additional context?**
Even though the response for the GET request to _dashboards/api/ism/smPolicies/test-daily-snapshot is as follows [which seems to be correct] -

```
{"ok":true,"response":{"id":"test-daily-snapshot","seqNo":18091,"primaryTerm":4,"policy":{"name":"test-daily-snapshot","description":"Policy for Daily Snapshot","schema_version":17,"creation":{"schedule":{"cron":{"expression":"0 0 * * *","timezone":"UTC"}}},"deletion":{"schedule":{"cron":{"expression":"0 0 * * *","timezone":"UTC"}},"condition":{"min_count":1,"max_count":100}},"snapshot_config":{"indices":"hot*,warm*","repository":"test23"},"schedule":{"interval":{"start_time":1684325948242,"period":1,"unit":"Minutes"}},"enabled":true,"last_updated_time":1684325948243,"enabled_time":1684325948242},"metadata":{"name":"test-daily-snapshot","creation":{"current_state":"CREATION_START","trigger":{"time":1684368000000}},"deletion":{"current_state":"DELETION_START","trigger":{"time":1684368000000}},"policy_seq_no":18091,"policy_primary_term":4,"enabled":true}}}
```

### PR DESCRIPTION
**Pull request by amsiglan**
### Description
This PR fixes below issues:
1. Snapshot flyout showing incorrect repository name
2. When editing a snapshot policy, the schedule input gets populated with default values instead of the policy schedule details.

### Issues Resolved
#823 , #822 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by getsaurabh02 — APPROVED** [review]

**Comment by lezzago** [comment]
Can we get some unit test for this?

File: public/pages/CreateSnapshotPolicy/components/CronSchedule/CronSchedule.tsx [hunk 1]
```diff
@@ -55,6 +55,25 @@ const CronSchedule = ({
   const [dayOfWeek, setWeek] = useState(initWeek);
   const [dayOfMonth, setMonth] = useState(initMonth);
 
+  // When edit policy is clicked, during the initial render DEFAULT values get passed
```
Comment (bowenlan-amzn) [inline public/pages/CreateSnapshotPolicy/components/CronSchedule/CronSchedule.tsx:58]: The miss here is thought useState will re-create those values every time

**Review by bowenlan-amzn — APPROVED** [review]

File: public/pages/CreateSnapshotPolicy/components/CronSchedule/CronSchedule.tsx (hunk 1 above)
Comment (amsiglan) [reply public/pages/CreateSnapshotPolicy/components/CronSchedule/CronSchedule.tsx:58]: Yeah
