### PR TITLE
Fix bug for shrink&close operation

### LINKED ISSUE #450: Bug fix for shrink&close operation
There are two bugs needed to fix:
1. Show `set write block` button when the source index's `index.blocks.write` setting is `false`.
2. Show a warning when the user wants to close the system indices.

### PR DESCRIPTION
**Pull request by gaobinlong**
Signed-off-by: Binlong Gao <gbinlong@amazon.com>

### Description
1. Fix bug for shrink index operation, shown `set write block` button when the source index' `index.blocks.write` setting is `false`.
2. Show warning when one or more system indices are selected to do close operation.
3. Add more unit tests for the change.

### Issues Resolved
#450 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx [hunk 1]
```diff
@@ -36,13 +39,21 @@ export default function CloseIndexModal(props: CloseIndexModalProps) {
     return null;
   }
 
+  const showWarning = selectedItems.map((item) => filterByMinimatch(item as string, SYSTEM_INDEX)).filter((it) => it).length > 0;
```
Comment (Hailong-am) [inline public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx:42]: could we combine map and filter into one filter?
```suggestion
  const showWarning = selectedItems.filter((item) => filterByMinimatch(item as string, SYSTEM_INDEX))).length > 0;
```

Comment (SuZhou-Joe) [inline public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx:42]: A filter will be enough, no need to chain a map .

**Review by Hailong-am — APPROVED** [review]

File: public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx [hunk 2]
```diff
@@ -145,7 +145,7 @@ export default class ShrinkIndexFlyout extends Component<ShrinkIndexProps, Shrin
       }
 
       const indexWriteBlock = get(sourceIndexSettings, [sourceIndex.index, "settings", INDEX_BLOCKS_WRITE_SETTING]);
-      if (!indexWriteBlock) {
+      if (indexWriteBlock != "true" && indexWriteBlock != true) {
```
Comment (SuZhou-Joe) [inline public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx:148]: use `!==` to indicate not equal will be safer

File: public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx [hunk 3]
```diff
@@ -174,7 +174,7 @@ export default class ShrinkIndexFlyout extends Component<ShrinkIndexProps, Shrin
       // Check whether `index.blocks.read_only` is set to `true`,
       // because shrink operation will timeout and then the new shrunken index's shards cannot be allocated.
       const indexReadOnlyBlock = get(sourceIndexSettings, [sourceIndex.index, "settings", INDEX_BLOCKS_READONLY_SETTING]);
-      if (!!indexReadOnlyBlock) {
+      if (indexReadOnlyBlock == "true" || indexReadOnlyBlock == true) {
```
Comment (SuZhou-Joe) [inline public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx:177]: The same, please use `===` to assert equal instead of `==`

File: public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx (hunk 1 above)
Comment (gaobinlong) [reply public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx]: Thanks, I will change it.

File: public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx (hunk 2 above)
Comment (gaobinlong) [reply public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx]: Thanks, I've made some change yet, can you help to take a look?

**Review by SuZhou-Joe — APPROVED** [review]

File: public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx [hunk 4]
```diff
@@ -36,13 +39,21 @@ export default function CloseIndexModal(props: CloseIndexModalProps) {
...
   return (
     <EuiModal onClose={onClose}>
       <EuiModalHeader>
         <EuiModalHeaderTitle>Close indices</EuiModalHeaderTitle>
       </EuiModalHeader>
 
       <EuiModalBody>
+        <>
+          <EuiCallOut color="warning" hidden={!showWarning}>
+            You are closing system-like index, please be careful before you do any change to it.
```
Comment (xluo-aws) [inline public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx:53]: Please change system-like to system index.

Comment (gaobinlong) [reply public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx:53]: OK, I'll change it.

File: public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx [hunk 5]
```diff
@@ -145,7 +145,7 @@ export default class ShrinkIndexFlyout extends Component<ShrinkIndexProps, Shrin
       }
 
       const indexWriteBlock = get(sourceIndexSettings, [sourceIndex.index, "settings", INDEX_BLOCKS_WRITE_SETTING]);
-      if (!indexWriteBlock) {
+      if (indexWriteBlock !== "true" && indexWriteBlock !== true) {
         const indexWriteBlockSettings = {
           "index.blocks.write": true,
```
[the remark this answers is not in the document]
Comment (gaobinlong) [reply public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx:150]: Yeah, the setting `index.blocks.write` is string in the response of the `Get Index Settings API`.
