### PR TITLE
snapshots_spec.js tests updated

### LINKED ISSUE #925: [Flaky Test] snapshots_spec.js
```
Running:  plugins/index-management-dashboards-plugin/snapshots_spec.js                  (13 of 17)


  Snapshots
    Repository can be created
      ✓ successfully creates a new repository (10943ms)
    Snapshot can be created
      ✓ successfully creates a new snapshot (12009ms)
    Snapshot can be restored
      1) Successfully restores indices from snapshot
    Snapshot can be deleted
      ✓ deletes snapshot successfully (120ms)


  3 passing (1m)
  1 failing

  1) Snapshots
       Snapshot can be restored
         Successfully restores indices from snapshot:
     AssertionError: Timed out retrying after 60000ms: Expected to find content: 'Restore snapshot' but never did.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js:1035:10)
```

https://github.com/opensearch-project/index-management-dashboards-plugin/actions/runs/6827404998/job/18569441857?pr=919

### PR DESCRIPTION
**Pull request by kohinoor98**
### Description
Added waits and made the flaky test more accurate by close observation and multiple runs.

### Issues Resolved
#925 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js [hunk 1]
```diff
@@ -53,10 +58,14 @@ describe("Snapshots", () => {
 
       // wait needed here to enable cypress to find "Take snapshot" button.  Timeout
       // cannot be used with cy.createIndex
-      cy.wait(5000);
+      cy.wait(12000);
```
Comment (bowenlan-amzn) [inline cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js:61]: @kohinoor98 this PR looks great, I think you are an expert on cypress now 😃

One thing I hope you can help think about and improve is to reduce all the hard coded wait time — basically the long test run time is a tech debt for us

Comment (kohinoor98) [reply cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js:61]: @bowenlan-amzn Thanks a lot 😂😂

Yes, I tried to keep it to a minimum; the OSD sometimes takes a lot of time, which is the main reason the test case is flaky. 

Would it be okay if the test case fails sometimes? Another way this issue is handled by other repos - https://github.com/opensearch-project/OpenSearch/pull/10544#issuecomment-1814995523

One of the other reasons the test fails is when the internet connection is unstable. Tested this by throttling the bandwidth to Slow 3g

We could go ahead and reduce the wait to 8500 if the above is ok with you. 

Thanks,
KC

Comment (bowenlan-amzn) [reply cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js:61]: I did some reading on cypress introduction guide
Since most of the cypress command support timeout, is the wait here same as increasing timeout to the next command? `cy.get([data-test-subj="takeSnapshotButton"], { timeout: 10000 })`

Comment (kohinoor98) [reply cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js:61]: Hi @bowenlan-amzn 

Really sorry I missed this. 

`cy.get` will wait until the object is available, or if the timeout is hit, it will skip and go on. If the object being looked for is available before the timeout, it will move to the following line.
`cy.wait` will wait for the hardcoded amount of time. In this case, it is a lot of time. The new issue #938 should be able to solve it.

We will know more over time!

Is there a blocker for this PR to be merged in?

KC

Comment (bowenlan-amzn) [reply cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js:61]: can you move the cy.wait into the its belowing cy.get timeout then, I just don't want to add more time directly onto the cy.wait.

Comment (kohinoor98) [reply cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js]: @bowenlan-amzn Done!

**Review by bowenlan-amzn — APPROVED** [review]

**Review by SuZhou-Joe — APPROVED** [review]
