### PR TITLE
rollups/transform: wait for page to render

### LINKED ISSUE #968: [AUTOCUT] Integration Test failed for indexManagementDashboards: 2.12.0 tar distribution
The integration test failed at distribution level for component indexManagementDashboards<br>Version: 2.12.0<br>Distribution: tar<br>Architecture: x64<br>Platform: linux<br><br>Please check the logs: https://build.ci.opensearch.org/job/integ-test-opensearch-dashboards/5119/display/redirect<br><br> * Test-report manifest:*<br> - https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.12.0/7123/linux/x64/tar/test-results/5119/integ-test/test-report.yml <br><br> _Note: Steps to reproduce, additional logs and other files can be found within the above test-report manifest. <br>Instructions of this test-report manifest can be found [here](https://github.com/opensearch-project/opensearch-build/tree/main/src/report_workflow#guide-on-test-report-manifest-from-ci)._

### PR DESCRIPTION
**Pull request by r1walz**
### Description

Adding intercepts and wait time to mitigate flaky tests.

### Issues Resolved

#968 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vikasvb90 — APPROVED** [review]

**Review by bowenlan-amzn — APPROVED** [review]

File: cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js [hunk 1]
```diff
@@ -242,28 +242,37 @@ describe("Rollups", () => {
...
       // Click into rollup job details page
       cy.get(`[data-test-subj="rollupLink_${ROLLUP_ID}"]`).click({
         force: true,
       });
 
       cy.contains(`${ROLLUP_ID}`);
 
-      // Disable button is enabled
-      cy.get(`[data-test-subj="disableButton"]`).should("not.be.disabled");
+      cy.wait("@getRollup").wait(2000);
```
Comment (bowenlan-amzn) [inline cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js:256]: I suppose getRollup will be triggered after line 250 click the rollup link, wondering is there a chance to already miss the getRollup call at this line.

Is there a way to chain this with line 250 like 
```
cy.get(`[data-test-subj="rollupLink_${ROLLUP_ID}"]`).click({
        force: true,
      }).wait("@getRollup");
```

Comment (r1walz) [reply cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js:256]: It should not be missed as [cypress waits for the request/response cycle to complete.](https://docs.cypress.io/api/commands/intercept#Waiting-on-a-request).

**Review by vikasvb90 — APPROVED** [review]
