### PR TITLE
[flaky test]solution for aliases.js 

### LINKED ISSUE #910: [Flaky Test] aliases.js
```
  Aliases
    can be searched / sorted / paginated
      1) "before each" hook for "successfully"


  0 passing (1m)
  1 failing

  1) Aliases
       can be searched / sorted / paginated
         "before each" hook for "successfully":
     AssertionError: Timed out retrying after 60000ms: Expected to find content: 'Rows per page' but never did.

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Aliases`
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/index-management-dashboards-plugin/aliases.js:132:8)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        7                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      6                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     1 minute, 7 seconds                                                              │
  │ Spec Ran:     plugins/index-management-dashboards-plugin/aliases.js                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

```

https://github.com/opensearch-project/index-management-dashboards-plugin/actions/runs/6117128934/job/16603304492

https://github.com/opensearch-project/index-management-dashboards-plugin/actions/runs/6714280704/job/18247266546?pr=909

https://github.com/opensearch-project/index-management-dashboards-plugin/actions/runs/6778757305/job/18425250051?pr=918

### PR DESCRIPTION
**Pull request by kohinoor98**
### Description
Solution: 
Intercepting the apiCaller POST call and waiting for the call to complete before moving on to check if the "Rows per page" is present.

The reason for it being flaky is that the `apiCaller` sometimes takes exteremely long time to return data as the number of elements are high and if the network tab is open in `cypress` while the test is being conducted the `API calls` take a very long time.

If the flaky test reoccurs then:
1. Change the number of POST calls in the `before` in `aliases.js`
2. Increase the timeout in the line below:
```bash
cy.wait("@apiCaller", { timeout: 120000 });
```

### Issues Resolved
#910 

### Check List
- [x] Commits are signed per the DCO using --signoff
- [x] All test cases are pasing for `aliases.js`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by SuZhou-Joe** [comment]
Nice try to fix the flaky test.

image
Actually the root cause that makes `alias.js` flaky is that OSD may take a long time to start(bundling specific js from source) and `alias.js` is the first test case. I'd recommend adding extra wait time before the `cy.visit(`${BASE_PATH}/app/${IM_PLUGIN_NAME}#/aliases`);` to wait for OSD start completely.

And please fix the DCO check.

**Comment by kohinoor98** [comment]
Hi @SuZhou-Joe 

Thanks lot for the reply. I will make the recommended change. I will also go ahead and run the test cases multiple times to ensure no other code is affected due to this change.

KC

**Comment by kohinoor98** [comment]
Hi @SuZhou-Joe

I have added a wait for the test case. 

Another solution would be to `ping` to a specific endpoint of OSD using `long polling` and try to see if `OSD` is ready. If it does not load in due time then the only option is throw an `error`. 
Is this a viable option? If yes, which end point would be most reliable to check if the `OSD` is ready?

Thanks,
KC

**Comment by SuZhou-Joe** [comment]
> Hi @SuZhou-Joe
> 
> I have added a wait for the test case.
> 
> Another solution would be to `ping` to a specific endpoint of OSD using `long polling` and try to see if `OSD` is ready. If it does not load in due time then the only option is throw an `error`. Is this a viable option? If yes, which end point would be most reliable to check if the `OSD` is ready?
> 
> Thanks, KC

Hi KC, I am afraid that for OSD there is not an endpoint that can check the status of bundling process, the only thing we can do should be more wait time for that.

**Comment by bowenlan-amzn** [comment]
@kohinoor98 I see the test is still failing here https://github.com/opensearch-project/index-management-dashboards-plugin/actions/runs/6843755781/job/18606696212?pr=920
I triggered a re-run

As for the fix, as @SuZhou-Joe mentioned, the problem is dashboard server is not ready yet, would you look at this part to tackle this problem
https://github.com/opensearch-project/index-management-dashboards-plugin/blame/1c8f0c660a6a7ef4960862e67ab8140a8d156691/.github/workflows/cypress-workflow.yml#L73-L75

**Comment by kohinoor98** [comment]
> @kohinoor98 I see the test is still failing here https://github.com/opensearch-project/index-management-dashboards-plugin/actions/runs/6843755781/job/18606696212?pr=920 I triggered a re-run
> 
> As for the fix, as @SuZhou-Joe mentioned, the problem is dashboard server is not ready yet, would you look at this part to tackle this problem https://github.com/opensearch-project/index-management-dashboards-plugin/blame/1c8f0c660a6a7ef4960862e67ab8140a8d156691/.github/workflows/cypress-workflow.yml#L73-L75

Hi @bowenlan-amzn 

I have increased the wait time to 420 seconds for now. If `aliases.js` fails to pass in the future based on [this](https://github.com/opensearch-project/index-management-dashboards-plugin/blame/1c8f0c660a6a7ef4960862e67ab8140a8d156691/.github/workflows/cypress-workflow.yml#L73-L75
), I recommend increasing the time for `cypress-workflow` and the wait in other test cases.

Another solution could be upgrading [cypress](https://www.npmjs.com/package/cypress).

Thanks,
KC

File: cypress/integration/plugins/index-management-dashboards-plugin/aliases.js [hunk 1]
```diff
@@ -26,11 +26,25 @@ describe("Aliases", () => {
...
+    });
+
     // Visit ISM OSD
     cy.visit(`${BASE_PATH}/app/${IM_PLUGIN_NAME}#/aliases`);
 
-    // Common text to wait for to confirm page loaded, give up to 60 seconds for initial load
-    cy.contains("Rows per page", { timeout: 60000 });
+    // Wait for 120 seconds for OSD to start.
+    // eslint-disable-next-line cypress/no-unnecessary-waiting
+    cy.wait(120000);
```
Comment (bowenlan-amzn) [inline cypress/integration/plugins/index-management-dashboards-plugin/aliases.js:41]: Don't want this to slow down the testing, I am looking for the way to make sure OSD starts, 2 things worth try

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/f6ce6e707035f791ed98a9edeab785d0785a8dbd/.github/workflows/cypress_workflow.yml#L149
https://github.com/opensearch-project/index-management-dashboards-plugin/blob/1c8f0c660a6a7ef4960862e67ab8140a8d156691/.github/workflows/cypress-workflow.yml#L75

For now you can just remove this wait, and we can try these 2 things in another PR

File: cypress/integration/plugins/index-management-dashboards-plugin/aliases.js [hunk 2]
```diff
@@ -26,11 +26,25 @@ describe("Aliases", () => {
...
+
+    // Wait for the API call to complete
+    cy.wait("@apiCaller", { timeout: 240000 });
```
Comment (bowenlan-amzn) [inline cypress/integration/plugins/index-management-dashboards-plugin/aliases.js:44]: Can you add some log around this, so we get an idea how long it wait for the fist vist aliases call

File: cypress/integration/plugins/index-management-dashboards-plugin/aliases.js (hunk 1 above)
Comment (kohinoor98) [reply cypress/integration/plugins/index-management-dashboards-plugin/aliases.js]: @bowenlan-amzn Done! Could you please create the appropriate issue for this and assign it to me? I will get started on it in a separate PR.

File: cypress/integration/plugins/index-management-dashboards-plugin/aliases.js (hunk 2 above)
Comment (kohinoor98) [reply cypress/integration/plugins/index-management-dashboards-plugin/aliases.js]: @bowenlan-amzn Done!

**Review by bowenlan-amzn — APPROVED** [review]

File: cypress/integration/plugins/index-management-dashboards-plugin/aliases.js (hunk 1 above)
Comment (bowenlan-amzn) [reply cypress/integration/plugins/index-management-dashboards-plugin/aliases.js]: Create one https://github.com/opensearch-project/index-management-dashboards-plugin/issues/938 but still need your comment to assign, thanks!

**Review by getsaurabh02 — APPROVED** [review]
